include:
  # Lewa połówka - peripheral (CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n w redox_left.conf)
  - board: nice_nano/nrf52840/zmk
    shield: redox_left
    artifact-name: redoxft_left

  # Prawa połówka - peripheral (default + jawnie w redox_right.conf)
  - board: nice_nano/nrf52840/zmk
    shield: redox_right
    artifact-name: redoxft_right

  # Dongle - central, USB, Studio
  - board: nice_nano/nrf52840/zmk
    shield: redoxft_dongle
    snippet: studio-rpc-usb-uart
    artifact-name: redoxft_dongle

  # Reset firmware - awaryjny do czyszczenia bondings
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset

