# Redox FT prawa połówka - PERIPHERAL
# Łączy się z donglem

# Peripheral role (default ale jawnie)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# RGB
CONFIG_ZMK_RGB_UNDERGLOW=y

# Wyświetlacz wyłączony
# CONFIG_ZMK_DISPLAY=y

# BT power boost
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Sleep
CONFIG_ZMK_SLEEP=y

# Debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7
