# Redox FT dongle central config
CONFIG_ZMK_KEYBOARD_NAME="Redox FT"
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Dongle should work over USB and be editable in ZMK Studio.
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_USB=y

# Keep pointing enabled because the Redox FT keymap uses mouse behaviors.
CONFIG_ZMK_POINTING=y

# Sleep is not important for a USB dongle, but harmless.
CONFIG_ZMK_SLEEP=y
