# Redox FT lewa połówka - PERIPHERAL
# Łączy się z donglem (nie z prawą połówką - to robi dongle)

# WYMUSZAMY peripheral role (nadpisuje shield default)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# RGB
CONFIG_ZMK_RGB_UNDERGLOW=y

# Wyświetlacz wyłączony
# CONFIG_ZMK_DISPLAY=y

# BT power boost dla lepszego zasięgu do dongla
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Sleep dla baterii
CONFIG_ZMK_SLEEP=y

# Eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7
