include:
  - board: nice_nano
    shield: redox_left
    artifact-name: redoxft_left

  - board: nice_nano
    shield: redox_right
    artifact-name: redoxft_right

  - board: nice_nano
    shield: redoxft_dongle
    artifact-name: redoxft_dongle
